repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0  # Use the latest version
    hooks:
      - id: detect-secrets
        name: Detect Secrets
        entry: detect-secrets-hook
        language: python
        args: ['--all-files']
        exclude: .secrets.baseline

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0  # Use the latest version
    hooks:
      - id: gitleaks
        name: Gitleaks
        entry: gitleaks protect
        language: golang
        args: ['--verbose']
        files: ''

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.6.6  # Use the latest version
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, snowflake]  # Example for Snowflake, change as needed

  - repo: https://github.com/psf/black
    rev: 21.12b0  # Use the latest version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.0.0
    hooks:
    - id: check-model-has-tests
      args: ["--test-cnt", "2", "--"]
