name: DBT CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  get-config:
    runs-on: ubuntu-latest

    outputs:
      deploy: ${{ steps.set_output_variables.outputs.deploy }}
      tests: ${{ steps.set_output_variables.outputs.tests }}
      pre_commit_hooks: ${{ steps.set_output_variables.outputs.pre_commit_hooks }}
      pre_commit_all_files: ${{ steps.set_output_variables.outputs.pre_commit_all_files }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read config file
        run: |
          CONFIG_PATH='./config.json'
          echo "Reading config file $CONFIG_PATH"
          DEPLOY=$(jq -r '.deploy' $CONFIG_PATH)
          TESTS=$(jq -r '.tests' $CONFIG_PATH)
          PRE_COMMIT_HOOKS=$(jq -r '."pre-commit".hooks | join(",")' $CONFIG_PATH)
          PRE_COMMIT_ALL_FILES=$(jq -r '."pre-commit"."all-files"' $CONFIG_PATH)

          echo "DEPLOY=$DEPLOY" >> $GITHUB_ENV
          echo "TESTS=$TESTS" >> $GITHUB_ENV
          echo "PRE_COMMIT_HOOKS=$PRE_COMMIT_HOOKS" >> $GITHUB_ENV
          echo "PRE_COMMIT_ALL_FILES=$PRE_COMMIT_ALL_FILES" >> $GITHUB_ENV

      - name: Print variables
        run: |
          echo "Should dbt run be executed: $DEPLOY"
          echo "Should tests be run: $TESTS"
          echo "Hooks to be run: $PRE_COMMIT_HOOKS"
          echo "Should hooks run over all files: $PRE_COMMIT_ALL_FILES"

      - name: Set output variables
        id: set_output_variables
        run: |
          echo "deploy=$DEPLOY" >> $GITHUB_OUTPUT
          echo "tests=$TESTS" >> $GITHUB_OUTPUT
          echo "pre_commit_hooks=$PRE_COMMIT_HOOKS" >> $GITHUB_OUTPUT
          echo "pre_commit_all_files=$PRE_COMMIT_ALL_FILES" >> $GITHUB_OUTPUT


  setup:
    needs: get-config
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install dbt-snowflake pre-commit

      - name: debug output variables
        run: |
          echo "${{ needs.get-config.outputs.pre_commit_hooks }}"
          echo "${{ needs.get-config.outputs.tests }}"
          echo "${{ needs.get-config.outputs.deploy }}"
          echo "${{ needs.get-config.outputs.pre_commit_all_files }}"

      - name: Generate cache key
        id: cache-key
        run: echo "::set-output name=key::${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}"

  pre-commit-checks:
    needs: [get-config, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ needs.setup.outputs.cache-key }}

      - name: debug output variables
        run: |
          echo "${{ needs.get-config.outputs.pre_commit_hooks }}"
          echo "${{ needs.get-config.outputs.tests }}"
          echo "${{ needs.get-config.outputs.deploy }}"
          echo "${{ needs.get-config.outputs.pre_commit_all_files }}"

      - name: Run pre-commit checks
        run: |
          source venv/bin/activate
          read -r ALL_FILES_FLAG <<< "${{ needs.get-config.outputs.pre_commit_all_files }}"
          echo $ALL_FILES_FLAG
          IFS=',' read -ra HOOKS <<< "${{ needs.get-config.outputs.pre_commit_hooks }}"
          if [ $ALL_FILES_FLAG ]; then
            echo $ALL_FILES_FLAG
          else
            echo $ALL_FILES_FLAG
          fi
          for hook in "${HOOKS[@]}"; do
            pre-commit run $hook --all-files
          done

  setup-dbt-profile:
    needs: pre-commit-checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up dbt profile
        run: |
          mkdir -p /home/runner/.dbt
          echo "$DBT_PROFILE_CONTENTS" > /home/runner/.dbt/profiles.yml
        env:
          DBT_PROFILE_CONTENTS: ${{ secrets.DBT_PROFILE_CONTENTS }}

  dbt-tests:
    needs: [get-config, setup, setup-dbt-profile]
    if: needs.get-config.outputs.tests == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Set up dbt profile
        run: |
            mkdir -p /home/runner/.dbt
            echo "$DBT_PROFILE_CONTENTS" > /home/runner/.dbt/profiles.yml
        env:
            DBT_PROFILE_CONTENTS: ${{ secrets.DBT_PROFILE_CONTENTS }}

      - name: Run dbt tests
        run: |
            source venv/bin/activate
            cd ./dbt_project
            dbt deps
            dbt test
        env:
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

  dbt-build:
    needs: [get-config, setup, setup-dbt-profile]
    if: needs.get-config.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Set up dbt profile
        run: |
            mkdir -p /home/runner/.dbt
            echo "$DBT_PROFILE_CONTENTS" > /home/runner/.dbt/profiles.yml
        env:
            DBT_PROFILE_CONTENTS: ${{ secrets.DBT_PROFILE_CONTENTS }}

      - name: Run dbt models
        run: |
            source venv/bin/activate
            cd ./dbt_project
            dbt deps
            dbt run
        env:
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
